//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallForPaper
    {
        public int Id { get; set; }
        public string Acronym { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime DeadlineAbstract { get; set; }
        public System.DateTime DeadlineProposal { get; set; }
        public Nullable<int> Topic_Id { get; set; }
        public int Topic_Id1 { get; set; }
		public string Topic_Name { get; set; }
    }
}
